// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpSbxg9P3uMryWnm--ooZiiCrLmzJE5kE',
    appId: '1:635310811545:web:634e092397930c7c170b08',
    messagingSenderId: '635310811545',
    projectId: 'smarthome-2b3d6',
    authDomain: 'smarthome-2b3d6.firebaseapp.com',
    storageBucket: 'smarthome-2b3d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvBWwgoqHcoaS9TdbCPqwTjSdkmnYW904',
    appId: '1:635310811545:android:868bbe5822c090bb170b08',
    messagingSenderId: '635310811545',
    projectId: 'smarthome-2b3d6',
    storageBucket: 'smarthome-2b3d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAok3dYLjugAOh__jkKkxTfQprRguRUDYw',
    appId: '1:635310811545:ios:5b328bd8f74b4c6d170b08',
    messagingSenderId: '635310811545',
    projectId: 'smarthome-2b3d6',
    storageBucket: 'smarthome-2b3d6.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpSbxg9P3uMryWnm--ooZiiCrLmzJE5kE',
    appId: '1:635310811545:web:e2eed8a9140cc824170b08',
    messagingSenderId: '635310811545',
    projectId: 'smarthome-2b3d6',
    authDomain: 'smarthome-2b3d6.firebaseapp.com',
    storageBucket: 'smarthome-2b3d6.firebasestorage.app',
  );
}
