// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJrvWwPgukuWA45_vZskDa4JZF0j4fi-E',
    appId: '1:846727777448:web:2dcabcac184ddbeccbc69d',
    messagingSenderId: '846727777448',
    projectId: 'smarthome-7ea8c',
    authDomain: 'smarthome-7ea8c.firebaseapp.com',
    storageBucket: 'smarthome-7ea8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX0fK8j_oQIxENpLFLtlhDeh12NOnlNFQ',
    appId: '1:846727777448:android:26dd8c8d49d97981cbc69d',
    messagingSenderId: '846727777448',
    projectId: 'smarthome-7ea8c',
    storageBucket: 'smarthome-7ea8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBObWhsx1yHZ4JOukhLCbc0EI278o9Fpy0',
    appId: '1:846727777448:ios:020cae4aba45b2efcbc69d',
    messagingSenderId: '846727777448',
    projectId: 'smarthome-7ea8c',
    storageBucket: 'smarthome-7ea8c.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJrvWwPgukuWA45_vZskDa4JZF0j4fi-E',
    appId: '1:846727777448:web:94da2a504a112083cbc69d',
    messagingSenderId: '846727777448',
    projectId: 'smarthome-7ea8c',
    authDomain: 'smarthome-7ea8c.firebaseapp.com',
    storageBucket: 'smarthome-7ea8c.firebasestorage.app',
  );
}
